---

- hosts: all
  sudo: True
  vars_files:
    - vars/default.yml
  tasks:
    - include_vars: vars/default.yml
    - action: group_by key={{ ansible_distribution }}
  roles:
    - common

- hosts: Ubuntu
  gather_facts: no
  sudo: True
  roles:
    - ubuntu
    - deploy
