---
- name: Create Chronos default conf file
  template: src=chronos_conf.j2 dest=/etc/default/chronos
    owner="root" group="root" mode=0664

- name: Create Chronos default init file
  template: src=chronos.j2 dest=/etc/init/chronos.conf
    owner="root" group="root" mode=0664
