---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add Mesosphere repo
  apt_repository:
    repo: "{{ chronos_apt_repo }}"
    state: present

- name: Install Chronos package
  apt: 
    pkg: chronos={{chronos_version}}-{{chronos_package_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
    state: present
    update_cache: yes
    cache_valid_time: 600
